name: curl
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch::pytorch
  - pytorch::torchvision
  - cudatoolkit=10.2
  - absl-py
  - pyparsing
  - pillow=6.1
  - pip
  - pip:
    - gym
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - scikit-image
